# Generated by Django 5.0.6 on 2024-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_msg_seen',
            field=models.BooleanField(default=False),
        ),
    ]
