# Generated by Django 5.0.6 on 2024-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
