# Generated by Django 5.0.6 on 2024-06-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_videocall_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocall',
            old_name='room',
            new_name='chat',
        ),
    ]
