# Generated by Django 5.0.6 on 2024-06-10 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_rename_room_videocall_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
